# Generated by Django 4.1.2 on 2023-08-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
